#
# Derived from
# https://github.com/steveno/ctags/blob/master/.travis.yml
#
language: c
compiler:
  - gcc
  - clang
branches:
  only:
    - master
script:
  - autoreconf -f -i -v
  - ./configure
  - make -j2
  - make check
