#
# Derived from
# https://github.com/steveno/ctags/blob/master/.travis.yml
#
language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y binutils-mingw-w64-i686 gcc-mingw-w64-i686  
script:
  - autoreconf -f -i -v
  - ./configure
  - make -j2
  - make check TRAVIS=1
  - make distclean
  - make -f mk_mingw.mak CC=i686-w64-mingw32-gcc
